package com.genesis.vistas;

import com.genesis.model.conexion;
import com.genesis.model.tableModel;
import util.Tools;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

public class wCambioPassword extends javax.swing.JInternalFrame implements ActiveFrame {
String menuName = "";
    String CRUD = "";
    private final tableModel tm;
    
    /**
     * Creates new form wCambioContrashena
     * @param menuName menu que se ha ejecutado en wPrincipal para abrir esta ventana
     */
    public wCambioPassword(String menuName) {
        initComponents();
        this.menuName = menuName;
        tm = new tableModel();
        tm.init("usuarios");
    }
    
    public void cambioPassword() {
        String msg;
        String strActClave;
        String strEncript;
        char ch_actclave[] = actclave.getPassword();
        char ch_newclave[] = newclave.getPassword();
        char ch_confclave[] = confclave.getPassword();
        //validar Longitud minima del Password actual
        if (ch_actclave.length < 4) {
            JOptionPane.showMessageDialog(rootPane, "Clave actual no puede ser menor a 4 caracteres ");
            actclave.requestFocus();
            return;
        }
        //validar Longitud minima del Password nuevo
        if (ch_newclave.length < 4) {
            JOptionPane.showMessageDialog(rootPane, "Nueva Clave debe ser mayor a 4 caracteres ");
            newclave.requestFocus();
            return;
        }
        //validar Longitud minima de la confirmacion del Password nuevo
        if (ch_confclave.length < 4) {
            JOptionPane.showMessageDialog(rootPane, "Nueva Clave debe ser mayor a 4 caracteres ");
            confclave.requestFocus();
            return;
        }

        if (Tools.validatePsw(ch_actclave)) { //Si true entonces contrase es valida
            //se consulta en DB si contrasena del usuario logueado esta bien
            Map<String, String> fields = new HashMap<>();
            Map<String, String> conditions = new HashMap<>();
            Map<String, String> rtn;
            fields.put("*", "*");
            strActClave = new String(ch_actclave);
            strEncript = Tools.encryptMD5(strActClave); //contrasena encriptada
            conditions.put("id", conexion.getUserId() + "");
            conditions.put("password", strEncript);
            rtn = tm.readRegisterById(fields, conditions);
            if (rtn.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Clave actual incorrecta");
                actclave.requestFocus();
                return;
            }
            String strNew, strConf;
            strNew = new String(ch_newclave);
            strConf = new String(ch_confclave);
            if (!strNew.equals(strConf)) {
                JOptionPane.showMessageDialog(rootPane, "Clave Nueva y Clave Confirmación no coinciden");
                newclave.requestFocus();
                return;
            }
            // Si Contrasena es correcta y contrasena nueva y confirmacion coinciden
            // entonces actualizar campo password en registro de usuario
            fields.clear();
            String nwPsw = new String(ch_newclave);
            strEncript = Tools.encryptMD5(nwPsw);
            fields.put("id", conexion.getUserId() + "");
            fields.put("password", strEncript);
            int count = tm.updateRegister(fields);
            
            if (count <= 0) {
            msg = "ERROR AL INTENTAR ACTUALIZAR CONTRASEÑA";
            } else {
            msg = "SE HA ACTUALIZADO CORRECTAMENTE LA CONTRASEÑA";
            this.actclave.setText("");
            this.newclave.setText("");
            this.confclave.setText("");
            }
        JOptionPane.showMessageDialog(this, msg, "ATENCIÓN...!", JOptionPane.DEFAULT_OPTION);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        actclave = new javax.swing.JPasswordField();
        newclave = new javax.swing.JPasswordField();
        confclave = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Abm Cambio Contraseña");
        setName("m_cambioContrasenha"); // NOI18N

        jLabel1.setText("Contraseña Actual");

        jLabel2.setText("Nueva Contraseña");

        jLabel3.setText("Confirmar Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actclave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newclave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confclave)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(actclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(confclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField actclave;
    private javax.swing.JPasswordField confclave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField newclave;
    // End of variables declaration//GEN-END:variables

    @Override
    public void imGrabar(String crud) {
        this.CRUD = crud;
        String msg;
        if (Tools.validarPermiso(conexion.getGrupoId(), menuName, crud) == 0) {
            msg = "PERMISO NO AUTORIZADO PARA REALIZAR ESTA OPERACIÓN";
            JOptionPane.showMessageDialog(this, msg, "ATENCIÓN.!!", JOptionPane.DEFAULT_OPTION);
        }
        cambioPassword();    
    } //fin imGrabar

    @Override
    public void imFiltrar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imActualizar(String crud) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imBorrar(String crud) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imNuevo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imBuscar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imPrimero() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imSiguiente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imAnterior() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imUltimo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imImprimir() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imInsDet() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imDelDet() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imCerrar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
