/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.genesis.vistas;

import com.genesis.model.conexion;
import com.genesis.model.tableModel;
import com.genesis.tabla.ModeloTabla;
import com.genesis.controladores.tableController;
import util.Tools;
import util.ComboBox;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class wPermisos extends javax.swing.JInternalFrame implements ActiveFrame {
    private boolean userSelectItem = false; // Variable para controlar si el usuario seleccionó un item de comboBox
    private Map<String, String> myData;
    private HashMap<String, String> myDet;
    private tableController tc;
    
    int idRol = conexion.getGrupoId();
    String menuName = "";
    String CRUD = "";

    public wPermisos(String menuName) {
        initComponents();
        this.menuName = menuName;
        myData = new HashMap<>();
        ComboBox.pv_cargar(jcbRol, "roles", " id, rol ", "id", "");
        tc = new tableController();
        tc.init("permisos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlTabla = new javax.swing.JScrollPane();
        jtDetalle = new javax.swing.JTable();
        jcbRol = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Permisos");

        jtDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Menu Id", "Menu", "VER", "CREATE", "READ", "UPDATE", "DELETE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrlTabla.setViewportView(jtDetalle);
        if (jtDetalle.getColumnModel().getColumnCount() > 0) {
            jtDetalle.getColumnModel().getColumn(3).setPreferredWidth(60);
            jtDetalle.getColumnModel().getColumn(3).setMaxWidth(60);
            jtDetalle.getColumnModel().getColumn(4).setPreferredWidth(60);
            jtDetalle.getColumnModel().getColumn(4).setMaxWidth(60);
            jtDetalle.getColumnModel().getColumn(5).setPreferredWidth(60);
            jtDetalle.getColumnModel().getColumn(5).setMaxWidth(60);
            jtDetalle.getColumnModel().getColumn(6).setPreferredWidth(60);
            jtDetalle.getColumnModel().getColumn(6).setMaxWidth(60);
            jtDetalle.getColumnModel().getColumn(7).setPreferredWidth(60);
            jtDetalle.getColumnModel().getColumn(7).setMaxWidth(60);
        }

        jcbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-Seleccione Rol" }));
        jcbRol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbRolItemStateChanged(evt);
            }
        });

        label1.setText("Elija Rol:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrlTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbRolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbRolItemStateChanged
    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED && userSelectItem) {
        mostrarMenus();
    }
        userSelectItem = true; // Marcar que el usuario seleccionó un item
    }//GEN-LAST:event_jcbRolItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jcbRol;
    private javax.swing.JTable jtDetalle;
    private java.awt.Label label1;
    private javax.swing.JScrollPane scrlTabla;
    // End of variables declaration//GEN-END:variables

    public void mostrarMenus() {
        limpiarTabla();
        DefaultTableModel dtm = (DefaultTableModel) jtDetalle.getModel();
        int row = 0;
        int rolid = Integer.parseInt(ComboBox.ExtraeCodigo(jcbRol.getSelectedItem().toString()));
        if (rolid == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un Rol válido.");
            return;
        }
        String sql, id, menuid, menu;
        Boolean showMenu, createReg, readReg, updateReg, deleteReg;

        sql = "SELECT p.id, p.menuid, m.menu, p.ver, p.c, p.r, p.u, p.d"
                + " FROM permisos p INNER JOIN menus m ON m.id = p.menuid "
                + "WHERE p.rolid = " + rolid;

        ResultSet rs;
        try {
            rs = conexion.ejecuteSQL(sql); //Esto devuelve un ResultSet
            while (rs.next()) {
                id = rs.getString("id");
                menuid = rs.getString("menuid");
                menu = rs.getString("menu");
                showMenu = (rs.getInt("ver") == 1) ? true : false;
                createReg = (rs.getInt("c") == 1) ? true : false;
                readReg = (rs.getInt("r") == 1) ? true : false;
                updateReg = (rs.getInt("u") == 1) ? true : false;
                deleteReg = (rs.getInt("d") == 1) ? true : false;

                dtm.addRow(new Object[]{id, menuid, menu, showMenu, createReg,
                    readReg, updateReg, deleteReg});
                row++;
            }//Fin while
        } //Fin TRY
        catch (SQLException ex) {
            Logger.getLogger(tableModel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//fin mostrarMenus();

    public void limpiarTabla() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jtDetalle.getModel();
            dtm.setRowCount(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }//fin limpiarTabla

    @Override
    public void imGrabar(String crud) {
        this.CRUD = crud;
        String msg;
        if (Tools.validarPermiso(conexion.getGrupoId(), menuName, crud) == 0) {
            msg = "NO TIENE PERMISO PARA REALIZAR ESTA OPERACIÓN ";
            JOptionPane.showMessageDialog(this, msg, "ATENCIÓN...!", JOptionPane.OK_OPTION);
            return;
        }
        
        int rowsAffected = 0;
        ArrayList<Map<String, String>> alPermisos = new ArrayList<>();
        //Sirve para poner en el map el nombre de la columna coincide con la estructura de la tabla
        String[] fields = {"id", "menuid", "menu", "ver", "c", "r", "u", "d"};
        myData.put("rolid", ComboBox.ExtraeCodigo(jcbRol.getSelectedItem().toString()));

        DefaultTableModel dftm = (DefaultTableModel) jtDetalle.getModel();
        int numRows = jtDetalle.getRowCount();
        int numCols = jtDetalle.getColumnCount();
        //rolid, ver, C, R, U, D, menuid
        Object fieldValue = null;  //Como las columnas almancenan datos distintos se tomo como Objetos
        for (int i = 0; i < numRows; i++) {
            alPermisos.clear();
            for (int j = 0; j < numCols; j++) {
                fieldValue = jtDetalle.getValueAt(i, j);
                if (fieldValue instanceof Boolean) {
                    if ((Boolean) fieldValue) {
                        myData.put(fields[j], "1");
                    } else {
                        myData.put(fields[j], "0");
                    }
                }
                if (fieldValue instanceof String) {
                    myData.put(fields[j], (String) fieldValue);
                }
            }

            alPermisos.add(myData);
            rowsAffected = this.tc.updateReg(alPermisos);

        }
        if (rowsAffected < 1) {
            msg = "ERROR AL INTENTAR ACTUALIZAR EL PERMISO";
        } else {
            msg = "SE HA ACTUALIZADO CORRECTAMENTE LOS PERMISOS";
        }
        JOptionPane.showMessageDialog(this, msg, "ATENCIÓN...!", JOptionPane.DEFAULT_OPTION);
    }//fin imGrabar

    @Override
    public void imFiltrar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imActualizar(String crud) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imBorrar(String crud) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imNuevo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imBuscar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imPrimero() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imSiguiente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imAnterior() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imUltimo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imImprimir() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imInsDet() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imDelDet() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void imCerrar() {
        setVisible(false);
        dispose();
    }
    
    private void setData() {
        myData.put("id", title);
        myData.put("rolid", title);
        myData.put("rol", title);
        myData.put("menuid", title);
        myData.put("menu", title);
        myData.put("ver", title);
        myData.put("c", title);
        myData.put("r", title);
        myData.put("u", title);
        myData.put("d", title);
    }
    
    private void resetData() {
    
    }
    
    private void fillView(){}

}//fin ventana
