package com.genesis.vistas;

import com.genesis.model.conexion;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import reportes.Reporte;
import util.Tools;

/**
 *
 * @author Ezequiel Cristaldo
 */
public class wPrincipal extends javax.swing.JFrame {
    private JInternalFrame[] w_abiertos;
    conexion con;
    
    /**
     * Creates new form Principal
     */
    public wPrincipal() {
        initComponents();
        this.setTitle("Genesis - Sistema de Gestion Comercial. Usuario:" + conexion.getUserName());
        this.setExtendedState(MAXIMIZED_BOTH);
        procesarMenus();
    }
    
    public wPrincipal(conexion con) {
        initComponents();
        this.con = con;
        this.setTitle("Genesis - Sistema de Gestion Comercial. Usuario:" + conexion.getUserName());
        this.setExtendedState(MAXIMIZED_BOTH);
        procesarMenus();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        mitenNuevo = new javax.swing.JMenuItem();
        mitenGuardar = new javax.swing.JMenuItem();
        mitenActualizar = new javax.swing.JMenuItem();
        mitenEliminar = new javax.swing.JMenuItem();
        mitenBuscar = new javax.swing.JMenuItem();
        mitenImprimir = new javax.swing.JMenuItem();
        mitenCerrarVentana = new javax.swing.JMenuItem();
        separadorArchivo = new javax.swing.JPopupMenu.Separator();
        mitenSalirSistema = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        mitenPrimero = new javax.swing.JMenuItem();
        mitenAnterior = new javax.swing.JMenuItem();
        mitenSiguiente = new javax.swing.JMenuItem();
        mitenUltimo = new javax.swing.JMenuItem();
        separadorEditar = new javax.swing.JPopupMenu.Separator();
        mitenInsertarDetalle = new javax.swing.JMenuItem();
        mitenEliminarDetalle = new javax.swing.JMenuItem();
        menuFichas = new javax.swing.JMenu();
        menuLocalidades = new javax.swing.JMenu();
        mitenDepartamento = new javax.swing.JMenuItem();
        mitenCiudad = new javax.swing.JMenuItem();
        mitenEmpleados = new javax.swing.JMenuItem();
        menuSeguridad = new javax.swing.JMenu();
        mitenUsuario = new javax.swing.JMenuItem();
        mitenRol = new javax.swing.JMenuItem();
        mitenMenu = new javax.swing.JMenuItem();
        mitenPermisos = new javax.swing.JMenuItem();
        mitenCambioPassword = new javax.swing.JMenuItem();
        menuStock = new javax.swing.JMenu();
        menuStockFichas = new javax.swing.JMenu();
        mitenCategoria = new javax.swing.JMenuItem();
        mitenProducto = new javax.swing.JMenuItem();
        mitenProductoDetalle = new javax.swing.JMenuItem();
        mitenDeposito = new javax.swing.JMenuItem();
        menuStockProcesos = new javax.swing.JMenu();
        menuStockInformes = new javax.swing.JMenu();
        mitenReporteProductos = new javax.swing.JMenuItem();
        menuCompra = new javax.swing.JMenu();
        menuCompraFichas = new javax.swing.JMenu();
        mitenProveedores = new javax.swing.JMenuItem();
        menuCompraProcesos = new javax.swing.JMenu();
        menuCompraInformes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 969, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        menuArchivo.setText("Archivo");
        menuArchivo.setName("menuArchivo"); // NOI18N
        menuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoActionPerformed(evt);
            }
        });

        mitenNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenNuevo.setText("Nuevo");
        mitenNuevo.setName("mitenNuevo"); // NOI18N
        mitenNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(mitenNuevo);

        mitenGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenGuardar.setText("Guardar");
        mitenGuardar.setName("mitenGuardar"); // NOI18N
        mitenGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(mitenGuardar);

        mitenActualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenActualizar.setText("Actualizar");
        mitenActualizar.setName("mitenActualizar"); // NOI18N
        mitenActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenActualizarActionPerformed(evt);
            }
        });
        menuArchivo.add(mitenActualizar);

        mitenEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenEliminar.setText("Eliminar");
        mitenEliminar.setName("mitenEliminar"); // NOI18N
        mitenEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenEliminarActionPerformed(evt);
            }
        });
        menuArchivo.add(mitenEliminar);

        mitenBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenBuscar.setText("Buscar");
        mitenBuscar.setName("mitenBuscar"); // NOI18N
        mitenBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenBuscarActionPerformed(evt);
            }
        });
        menuArchivo.add(mitenBuscar);

        mitenImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenImprimir.setText("Imprimir");
        mitenImprimir.setName("mitenImprimir"); // NOI18N
        menuArchivo.add(mitenImprimir);

        mitenCerrarVentana.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenCerrarVentana.setText("Cerrar Ventana");
        mitenCerrarVentana.setName("mitenCerrarVentana"); // NOI18N
        menuArchivo.add(mitenCerrarVentana);
        menuArchivo.add(separadorArchivo);

        mitenSalirSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenSalirSistema.setText("Salir");
        mitenSalirSistema.setName("mitenSalirSistema"); // NOI18N
        mitenSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenSalirSistemaActionPerformed(evt);
            }
        });
        menuArchivo.add(mitenSalirSistema);

        barraMenu.add(menuArchivo);

        menuEditar.setText("Editar");
        menuEditar.setName("menuEditar"); // NOI18N

        mitenPrimero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_UP, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenPrimero.setText("Primero");
        mitenPrimero.setName("mitenPrimero"); // NOI18N
        mitenPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenPrimeroActionPerformed(evt);
            }
        });
        menuEditar.add(mitenPrimero);

        mitenAnterior.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenAnterior.setText("Anterior");
        mitenAnterior.setName("mitenAnterior"); // NOI18N
        menuEditar.add(mitenAnterior);

        mitenSiguiente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenSiguiente.setText("Siguiente");
        mitenSiguiente.setName("mitenSiguiente"); // NOI18N
        menuEditar.add(mitenSiguiente);

        mitenUltimo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DOWN, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitenUltimo.setText("Último");
        mitenUltimo.setName("mitenUltimo"); // NOI18N
        menuEditar.add(mitenUltimo);
        menuEditar.add(separadorEditar);

        mitenInsertarDetalle.setText("Ins. Detalle");
        mitenInsertarDetalle.setName("mitenInsertarDetalle"); // NOI18N
        menuEditar.add(mitenInsertarDetalle);

        mitenEliminarDetalle.setText("Del. Detalle");
        mitenEliminarDetalle.setName("mitenEliminarDetalle"); // NOI18N
        menuEditar.add(mitenEliminarDetalle);

        barraMenu.add(menuEditar);

        menuFichas.setText("Fichas");
        menuFichas.setName("menuFichas"); // NOI18N

        menuLocalidades.setText("Localidades");
        menuLocalidades.setName("menuLocalidades"); // NOI18N

        mitenDepartamento.setText("Departamento");
        mitenDepartamento.setName("mitenDepartamento"); // NOI18N
        mitenDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenDepartamentoActionPerformed(evt);
            }
        });
        menuLocalidades.add(mitenDepartamento);

        mitenCiudad.setText("Ciudad");
        mitenCiudad.setName("mitenCiudad"); // NOI18N
        menuLocalidades.add(mitenCiudad);

        menuFichas.add(menuLocalidades);

        mitenEmpleados.setText("Empleados");
        mitenEmpleados.setName("mitenEmpleados"); // NOI18N
        mitenEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenEmpleadosActionPerformed(evt);
            }
        });
        menuFichas.add(mitenEmpleados);
        mitenEmpleados.getAccessibleContext().setAccessibleName("mitenEmpleados");

        barraMenu.add(menuFichas);
        menuFichas.getAccessibleContext().setAccessibleName("menuRegistros");

        menuSeguridad.setText("Seguridad");
        menuSeguridad.setName("menuSeguridad"); // NOI18N

        mitenUsuario.setText("Usuario");
        mitenUsuario.setName("mitenUsuario"); // NOI18N
        mitenUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenUsuarioActionPerformed(evt);
            }
        });
        menuSeguridad.add(mitenUsuario);

        mitenRol.setText("Rol");
        mitenRol.setName("mitenRol"); // NOI18N
        menuSeguridad.add(mitenRol);

        mitenMenu.setText("Menu");
        mitenMenu.setName("mitenMenu"); // NOI18N
        mitenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenMenuActionPerformed(evt);
            }
        });
        menuSeguridad.add(mitenMenu);

        mitenPermisos.setText("Permisos");
        mitenPermisos.setName("mitenPermisos"); // NOI18N
        mitenPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenPermisosActionPerformed(evt);
            }
        });
        menuSeguridad.add(mitenPermisos);

        mitenCambioPassword.setText("Cambiar Contraseña");
        mitenCambioPassword.setName("mitenCambioPassword"); // NOI18N
        mitenCambioPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenCambioPasswordActionPerformed(evt);
            }
        });
        menuSeguridad.add(mitenCambioPassword);

        barraMenu.add(menuSeguridad);

        menuStock.setText("Stock");
        menuStock.setName("menuStock"); // NOI18N

        menuStockFichas.setText("Fichas");
        menuStockFichas.setName("menuStockFichas"); // NOI18N

        mitenCategoria.setText("Categoria");
        mitenCategoria.setName("mitenCategoria"); // NOI18N
        mitenCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenCategoriaActionPerformed(evt);
            }
        });
        menuStockFichas.add(mitenCategoria);

        mitenProducto.setText("Producto");
        mitenProducto.setName("mitenProducto"); // NOI18N
        mitenProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenProductoActionPerformed(evt);
            }
        });
        menuStockFichas.add(mitenProducto);

        mitenProductoDetalle.setText("Detalle Producto");
        mitenProductoDetalle.setName("mitenProductoDetalle"); // NOI18N
        menuStockFichas.add(mitenProductoDetalle);

        mitenDeposito.setText("Depósito");
        mitenDeposito.setName("mitenDeposito"); // NOI18N
        mitenDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenDepositoActionPerformed(evt);
            }
        });
        menuStockFichas.add(mitenDeposito);

        menuStock.add(menuStockFichas);

        menuStockProcesos.setText("Procesos");
        menuStock.add(menuStockProcesos);

        menuStockInformes.setText("Informes");

        mitenReporteProductos.setText("Reporte de Productos");
        mitenReporteProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenReporteProductosActionPerformed(evt);
            }
        });
        menuStockInformes.add(mitenReporteProductos);

        menuStock.add(menuStockInformes);

        barraMenu.add(menuStock);

        menuCompra.setText("Compra");
        menuCompra.setName("menuCompra"); // NOI18N

        menuCompraFichas.setText("Fichas");

        mitenProveedores.setText("Proveedores");
        mitenProveedores.setName("mitenProveedores"); // NOI18N
        mitenProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenProveedoresActionPerformed(evt);
            }
        });
        menuCompraFichas.add(mitenProveedores);
        mitenProveedores.getAccessibleContext().setAccessibleName("mitenProveedores");

        menuCompra.add(menuCompraFichas);

        menuCompraProcesos.setText("Procesos");
        menuCompra.add(menuCompraProcesos);

        menuCompraInformes.setText("Informes");
        menuCompra.add(menuCompraInformes);

        barraMenu.add(menuCompra);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    /**Iniciar y Mostrar Ventana Empleados*/
    private void mitenEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenEmpleadosActionPerformed
        JMenuItem m = (JMenuItem) evt.getSource();
        wEmpleados v_empleados = new wEmpleados(m.getName());
        // Verificar si ya existe una ventana abierta del mismo tipo
        if (encuentraVentana(v_empleados)) {
            return; // Si ya existe, no hacemos nada más
        }
        // Si no existe, mostramos la ventana y la centramos
        mostrarVentana(v_empleados);
        centrar(v_empleados);        
    }//GEN-LAST:event_mitenEmpleadosActionPerformed

    /**Ejecuta ActiveFrame.crearRegistro*/
    private void mitenGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenGuardarActionPerformed
            ActiveFrame activeFrame = getActiveFrame();
            if(activeFrame == null){
                return;
            }
            activeFrame.imGrabar("C");
    }//GEN-LAST:event_mitenGuardarActionPerformed

    private void mitenEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenEliminarActionPerformed
            ActiveFrame activeFrame = getActiveFrame();
            if(activeFrame == null){
                return;
            }
            activeFrame.imBorrar("D");
    }//GEN-LAST:event_mitenEliminarActionPerformed

    private void mitenPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenPrimeroActionPerformed
        ActiveFrame activeFrame = getActiveFrame();
        if(activeFrame == null){
            return;
        }
        //activeFrame.procesarSolicitud("F");
    }//GEN-LAST:event_mitenPrimeroActionPerformed

    /**Limpiar formulario de la vista*/
    private void mitenNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenNuevoActionPerformed
        ActiveFrame activeFrame = getActiveFrame();
        if(activeFrame == null){
            return;
        }
        activeFrame.imNuevo();    
    }//GEN-LAST:event_mitenNuevoActionPerformed

    private void mitenActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenActualizarActionPerformed
        ActiveFrame activeFrame = getActiveFrame();
        if(activeFrame == null){
            return;
        }
        activeFrame.imActualizar("U");
    }//GEN-LAST:event_mitenActualizarActionPerformed

    private void mitenBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenBuscarActionPerformed
        ActiveFrame activeFrame = getActiveFrame();
        if(activeFrame == null){
            return;
        }
        activeFrame.imFiltrar();
        
    }//GEN-LAST:event_mitenBuscarActionPerformed

    private void mitenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenMenuActionPerformed
        JMenuItem m = (JMenuItem) evt.getSource();
        wMenu view = new wMenu(m.getName());
        // Verificar si ya existe una ventana abierta del mismo tipo
        if (encuentraVentana(view)) {
            return; // Si ya existe, no hacemos nada más
        }
        // Si no existe, mostramos la ventana y la centramos
        mostrarVentana(view);
        centrar(view); 
    }//GEN-LAST:event_mitenMenuActionPerformed

    private void mitenUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenUsuarioActionPerformed
        JMenuItem m = (JMenuItem) evt.getSource();
        wUsuario v_usuario = new wUsuario(m.getName());
        // Verificar si ya existe una ventana abierta del mismo tipo
        if (encuentraVentana(v_usuario)) {
            return; // Si ya existe, no hacemos nada más
        }
        // Si no existe, mostramos la ventana y la centramos
        mostrarVentana(v_usuario);
        centrar(v_usuario);
    }//GEN-LAST:event_mitenUsuarioActionPerformed

    private void mitenPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenPermisosActionPerformed
        JMenuItem m = (JMenuItem) evt.getSource();
        wPermisos view = new wPermisos(m.getName());
        if(encuentraVentana(view)){
            return;
        }
        mostrarVentana(view);
        centrar(view);        // TODO add your handling code here:
    }//GEN-LAST:event_mitenPermisosActionPerformed

    private void mitenProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenProveedoresActionPerformed
        JMenuItem m = (JMenuItem) evt.getSource();
        wProveedor view = new wProveedor(m.getName());
        if (encuentraVentana(view)){
            return;
        }
        mostrarVentana(view);
        centrar(view);
    }//GEN-LAST:event_mitenProveedoresActionPerformed

    private void mitenCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenCategoriaActionPerformed
        JMenuItem m = (JMenuItem) evt.getSource();
        wCategoria view = new wCategoria(m.getName());
        if (encuentraVentana(view)){
            return;
        }
        mostrarVentana(view);
        centrar(view);
    }//GEN-LAST:event_mitenCategoriaActionPerformed

    private void mitenProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenProductoActionPerformed
        JMenuItem m = (JMenuItem) evt.getSource();
        wProducto view = new wProducto(m.getName());
        if (encuentraVentana(view)){
            return;
        }
        mostrarVentana(view);
        centrar(view);
    }//GEN-LAST:event_mitenProductoActionPerformed

    private void menuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoActionPerformed

    }//GEN-LAST:event_menuArchivoActionPerformed

    private void mitenSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenSalirSistemaActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea salir del sistema?");
        if(respuesta == 0){
            System.exit(0); 
        }  
    }//GEN-LAST:event_mitenSalirSistemaActionPerformed

    private void mitenCambioPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenCambioPasswordActionPerformed
        JMenuItem m = (JMenuItem) evt.getSource();
        wCambioPassword view = new wCambioPassword(m.getName());
        if (encuentraVentana(view)){
            return;
        }
        mostrarVentana(view);
        centrar(view);
    }//GEN-LAST:event_mitenCambioPasswordActionPerformed

    private void mitenDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenDepositoActionPerformed
        JMenuItem m = (JMenuItem) evt.getSource();
        wDeposito view = new wDeposito(m.getName());
        if (encuentraVentana(view)){
            return;
        }
        mostrarVentana(view);
        centrar(view);
    }//GEN-LAST:event_mitenDepositoActionPerformed

    private void mitenReporteProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenReporteProductosActionPerformed
        Reporte r = new Reporte("productosreport", "vFiltroProductos", this);
        r.setTitle("Reporte de Productos");
        r.setClosable(true);
        mostrarVentana(r);
        centrar(r);
    }//GEN-LAST:event_mitenReporteProductosActionPerformed

    private void mitenDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenDepartamentoActionPerformed
        JMenuItem m = (JMenuItem) evt.getSource();
        wDepartamento view = new wDepartamento(m.getName());
        if (encuentraVentana(view)){
            return;
        }
        mostrarVentana(view);
        centrar(view);
    }//GEN-LAST:event_mitenDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar barraMenu;
    public static javax.swing.JDesktopPane desktop;
    public javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuCompra;
    private javax.swing.JMenu menuCompraFichas;
    private javax.swing.JMenu menuCompraInformes;
    private javax.swing.JMenu menuCompraProcesos;
    private javax.swing.JMenu menuEditar;
    public javax.swing.JMenu menuFichas;
    private javax.swing.JMenu menuLocalidades;
    private javax.swing.JMenu menuSeguridad;
    private javax.swing.JMenu menuStock;
    private javax.swing.JMenu menuStockFichas;
    private javax.swing.JMenu menuStockInformes;
    private javax.swing.JMenu menuStockProcesos;
    private javax.swing.JMenuItem mitenActualizar;
    public javax.swing.JMenuItem mitenAnterior;
    private javax.swing.JMenuItem mitenBuscar;
    private javax.swing.JMenuItem mitenCambioPassword;
    private javax.swing.JMenuItem mitenCategoria;
    private javax.swing.JMenuItem mitenCerrarVentana;
    private javax.swing.JMenuItem mitenCiudad;
    private javax.swing.JMenuItem mitenDepartamento;
    private javax.swing.JMenuItem mitenDeposito;
    public javax.swing.JMenuItem mitenEliminar;
    private javax.swing.JMenuItem mitenEliminarDetalle;
    public javax.swing.JMenuItem mitenEmpleados;
    public javax.swing.JMenuItem mitenGuardar;
    private javax.swing.JMenuItem mitenImprimir;
    private javax.swing.JMenuItem mitenInsertarDetalle;
    private javax.swing.JMenuItem mitenMenu;
    private javax.swing.JMenuItem mitenNuevo;
    private javax.swing.JMenuItem mitenPermisos;
    public javax.swing.JMenuItem mitenPrimero;
    private javax.swing.JMenuItem mitenProducto;
    private javax.swing.JMenuItem mitenProductoDetalle;
    public javax.swing.JMenuItem mitenProveedores;
    private javax.swing.JMenuItem mitenReporteProductos;
    private javax.swing.JMenuItem mitenRol;
    private javax.swing.JMenuItem mitenSalirSistema;
    public javax.swing.JMenuItem mitenSiguiente;
    public javax.swing.JMenuItem mitenUltimo;
    private javax.swing.JMenuItem mitenUsuario;
    private javax.swing.JPopupMenu.Separator separadorArchivo;
    private javax.swing.JPopupMenu.Separator separadorEditar;
    // End of variables declaration//GEN-END:variables

    public ActiveFrame getActiveFrame(){
        //Obtener el JInternalFrame activo desde el JDesktopPane
        ActiveFrame v = (ActiveFrame) desktop.getSelectedFrame();
        if(v == null){
        JOptionPane.showMessageDialog(null, "No hay ventana activa...", "Atencion...", JOptionPane.OK_OPTION);
        }
        return v;
    }
    
    public boolean encuentraVentana(JInternalFrame w){
        w_abiertos = desktop.getAllFrames();
        int len = w_abiertos.length;
        int i;
        if (len > 0){
            for(i = 0; i < len; i++){
                if(w_abiertos[i].getTitle().equals(w.getTitle())){
                return true;
                }
            }
        }
        return false;
    }
    
    public void mostrarVentana(javax.swing.JInternalFrame frame){
        w_abiertos = desktop.getAllFrames();
        if(encuentraVentana(frame)){
        return;
        }
        desktop.add(frame);
        frame.setVisible(true);
        try{
            frame.setSelected(true);
        }catch(PropertyVetoException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.OK_OPTION);
        }
    }
    
    public void centrar(JInternalFrame internalFrame){
        int x = (desktop.getWidth() / 2) - internalFrame.getWidth() / 2;
        int y = (desktop.getHeight()/ 2) - internalFrame.getHeight() / 2;
        
        if (internalFrame.isShowing()){
            internalFrame.setLocation(x, y);
        } else{
            desktop.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }
    
    private void procesarMenus() {
        javax.swing.JMenu m_menu;
        javax.swing.JMenu m_submenu;
        javax.swing.JMenu m_item;
        javax.swing.JMenu m_subitem;
        String s_nombre = "", s_text = "", s_menu = "";
        int cantm = 0, cod = 0, cants = 0, canti = 0, cantj = 0, li_grabados = 0;
        int li_grabar = 0, li_cm, li_csm, li_ci, li_csi; //utilizo para saber si 1-grabo o 0-modifico

        cantm = (int) barraMenu.getMenuCount();
        cod = 0;
        if (cantm > 0) {
            li_cm = 0;
            for (int m = 0; m < cantm; m++) {
                s_nombre = "";
                li_cm++;

                if (barraMenu.getMenu(m) instanceof javax.swing.JMenu) {
                    cod++;
                    m_menu = barraMenu.getMenu(m);
                    s_nombre = m_menu.getName(); // Obtener el texto visible del menú
                    System.out.println("nombreMenu:"+s_nombre);
                    if (Tools.validarPermiso(conexion.getGrupoId(), s_nombre, "ver") == 0) {
                        System.out.println("validarpermiso == 0");
                        m_menu.setVisible(false);
                        cants = 0; //Tenemos que prevenir que haga el siguiente if(cants >0)
                    } else {
                        System.out.println("validarPermiso == 1");
                        m_menu.setVisible(true);
                        cants = m_menu.getItemCount();
                    }
                }

                if (cants > 0) {
                    li_csm = 1;
                    m_menu = barraMenu.getMenu(m);
                    for (int s = 0; s < cants; s++) {
                        s_nombre = "";
                        if (m_menu.getItem(s) instanceof javax.swing.JMenu) {
                            cod++;
                            m_submenu = (javax.swing.JMenu) m_menu.getItem(s);
                            s_nombre = m_submenu.getName();
                            if (Tools.validarPermiso(conexion.getGrupoId(), s_nombre, "ver") == 0) {
                                System.out.println("miten == 0");
                                m_submenu.setVisible(false);
                                cants = 0; //Tenemos que prevenir que haga el siguiente if(cants >0)
                            } else {
                                System.out.println("miten == 1");
                                m_submenu.setVisible(true);
                                canti = m_submenu.getItemCount();
                                li_csm++;
                            }                            
                        } else {
                            if (m_menu.getItem(s) instanceof javax.swing.JMenuItem) {
                                cod++;
                                s_nombre = m_menu.getItem(s).getName();
                                if (Tools.validarPermiso(conexion.getGrupoId(), s_nombre, "ver") == 0) {
                                    System.out.println("mitenhijo == 0");
                                    m_menu.getItem(s).setVisible(false);
                                    canti = 0; //Tenemos que prevenir que haga el siguiente if(cants >0)
                                } else {
                                    System.out.println("mitenhijo == 1");
                                    m_menu.getItem(s).setVisible(true);
                                    canti = 0;
                                    li_csm++;
                                }
                            } else {
                                canti = 0;
                            }
                        }
                        
                        if (canti > 0) {
                            li_ci = 1;
                            m_submenu = (javax.swing.JMenu) m_menu.getItem(s);
                            for (int i = 0; i < canti; i++) {
                                s_nombre = "";
                                if (m_submenu.getItem(i) instanceof javax.swing.JMenu) {
                                    cod++;
                                    m_item = (javax.swing.JMenu) m_submenu.getItem(i);
                                    s_nombre = m_item.getName();
                                    if (Tools.validarPermiso(conexion.getGrupoId(), s_nombre, "ver") == 0) {
                                        m_item.setVisible(false);
                                        cantj = 0; //Tenemos que prevenir que haga el siguiente if(cants >0)
                                    } else {
                                        m_item.setVisible(true);
                                        cantj = m_item.getItemCount();
                                        li_ci++;
                                    }
                                } else {
                                    if (m_submenu.getItem(i) instanceof javax.swing.JMenuItem) {
                                        cod++;
                                        s_nombre = m_submenu.getItem(i).getName();
                                        if (Tools.validarPermiso(conexion.getGrupoId(), s_nombre, "ver") == 0) {
                                            m_submenu.getItem(i).setVisible(false);
                                            cantj = 0; //Tenemos que prevenir que haga el siguiente if(cants >0)
                                        } else {
                                            m_submenu.getItem(i).setVisible(true);
                                            cantj = 0;
                                            li_ci++;
                                        }
                                    } else {
                                        cantj = 0;
                                    }
                                }
                                //System.out.println(s_nombre+" con "+cantj+" subitems");
                                if (cantj > 0) {
                                    li_csi = 0;
                                    for (int j = 0; j < cantj; j++) {
                                        cod++;
                                        s_nombre = "";
                                        s_text = "";
                                        m_subitem = (javax.swing.JMenu) m_menu.getItem(i);
                                        li_csi++;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//fin procesarMenus
}
