package reportes;

import util.ComboBox;
import java.util.HashMap;

public class vFiltroSeguimientoProducto extends javax.swing.JDialog {
    private int returnStatus = RET_CANCEL;
    private static final int RET_CANCEL = 0;
    private static final int RET_OK = 0;
    HashMap par = new HashMap();
    
    /**
     * Creates new form vFiltroProductos
     * @param parent la ventana principal
     * @param modal true. Indica si el diálogo es modal, es decir, si bloquea la interacción con otras ventanas mientras está abierto.
     */
    public vFiltroSeguimientoProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ComboBox.pv_cargar(jcbDeposito, "depositos", " id, nombre ", "id", "");
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAceptar = new javax.swing.JButton();
        lblDeposito = new javax.swing.JLabel();
        jButtonCerrar = new javax.swing.JButton();
        lblCodBarra = new javax.swing.JLabel();
        jcbDeposito = new javax.swing.JComboBox<>();
        tf_codbarra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAceptar.setText("ACEPTAR");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        lblDeposito.setText("DEPOSITO");

        jButtonCerrar.setText("CANCELAR");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        lblCodBarra.setText("COD BARRA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addGap(93, 93, 93)
                        .addComponent(jButtonCerrar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_codbarra))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcbDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodBarra)
                    .addComponent(tf_codbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeposito)
                    .addComponent(jcbDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCerrar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vFiltroSeguimientoProducto dialog = new vFiltroSeguimientoProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    //Operaciones realizadas y luego cierra la ventana
    private void doClose (int retStatus){
        returnStatus = retStatus;
        getParameters();
        setVisible(false);
        dispose();       
    }

    private void getParameters(){
        String argcodbarra = "";
        if ("".equals(tf_codbarra.getText())){
            argcodbarra = "";
        }else{
          argcodbarra = tf_codbarra.getText();
        }
        
        String argdepositoo = ComboBox.ExtraeCodigo(jcbDeposito.getSelectedItem().toString());
        if (argdepositoo.equals("")){ argdepositoo = "1"; } 
        int argdeposito = Integer.parseInt(argdepositoo);
        
        par.put("productoId",argcodbarra);
        par.put("depositoId",argdeposito);
    } //Fin getParameters
    
    public void setParams(HashMap p){
        this.par = p;
    }
    public int getReturnStatus(){
        return returnStatus;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JComboBox<String> jcbDeposito;
    private javax.swing.JLabel lblCodBarra;
    private javax.swing.JLabel lblDeposito;
    private javax.swing.JTextField tf_codbarra;
    // End of variables declaration//GEN-END:variables
}
